# Generated by Django 4.0.3 on 2022-03-02 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.genre'),
        ),
    ]
