# Generated by Django 4.0.3 on 2022-03-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_feature_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
