# Generated by Django 4.0.3 on 2022-03-03 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_article_excerpt_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[+/%]', inverse_match=True)]),
        ),
    ]
