# Generated by Django 4.0.3 on 2022-03-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_comment_time_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
    ]
