# Generated by Django 4.0.3 on 2022-03-04 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_article_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('[+/%]', inverse_match=True)]),
        ),
    ]
