# Generated by Django 4.0.3 on 2022-03-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_home_article',
            field=models.BooleanField(default=False),
        ),
    ]
