# Generated by Django 4.0.3 on 2022-03-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
